name: Auto Cite by Crawler

on:
  push:
    branches:
      - main
    paths:
      - "_config.yaml"
  pull_request:
    paths:
      - "_config.yaml"
  # workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 1"

jobs:
  update_research:
    name: Auto Cite by Crawler
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: python -m pip install --upgrade --requirement ./auto-cite/requirements.txt
      - name: Installed package list
        run: apt list --installed
      # - name: Remove Chrome
      #   run: sudo apt purge google-chrome-stable
      # - name: Remove default Chromium
      #   run: sudo apt purge chromium-browser
      # - name: Install a new Chromium
      #   run: sudo apt-get install -y chromium-browser=119.0.6045.0
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Build updated citations
        run: python ./auto-cite/auto-cite-by-crawler.py
        timeout-minutes: 600
      - name: Commit updated citations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/citations.yaml"
          commit_message: "Generate citations by crawler"
          push_options: --force
